load("//software/build_defs:mrav.bzl", "mrav_binary")

mrav_binary(
    name = "loop",
    srcs = [
        "loop.mrav",
    ],
    out = "loop.bin",
    visibility = [
        "//visibility:public",
    ],
)
