load("@rules_go//go:def.bzl", "go_library")

package(
    default_visibility = [
        "//visibility:public",
    ],
)

go_library(
    name = "isa",
    srcs = [
        "isa.go",
        "parsing.go",
    ],
    importpath = "mrav/isa",
)
