load("@rules_go//go:def.bzl", "go_library")

package(
    default_visibility = [
        "//visibility:public",
    ],
)

go_library(
    name = "system",
    srcs = [
        "system.go",
    ],
    importpath = "mrav/system",
)
